{% set version = "0.5.0" %}

package:
  name: r-ggridges
  version: {{ version|replace("-", "_") }}

source:
  fn: ggridges_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/ggridges_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/ggridges/ggridges_{{ version }}.tar.gz
  sha256: 124bc84044e56728fa965682f8232fc868f2af7d3eb7276f6b0df53be8d2dbfe

build:
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-ggplot2 >=2.2.0
    - r-plyr >=1.8.0
    - r-scales >=0.4.1
    - r-withr >=2.1.1

  run:
    - r-base
    - r-ggplot2 >=2.2.0
    - r-plyr >=1.8.0
    - r-scales >=0.4.1
    - r-withr >=2.1.1

test:
  commands:
    - $R -e "library('ggridges')"  # [not win]
    - "\"%R%\" -e \"library('ggridges')\""  # [win]

about:
  home: https://github.com/clauswilke/ggridges
  license: GPL-2
  summary: Ridgeline plots provide a convenient way of visualizing changes in distributions over
    time or space. This package enables the creation of such plots in 'ggplot2'.
  license_family: GPL2

extra:
  recipe-maintainers:
    - bgruening
    - daler
    - johanneskoester
    - rvalieris
