{% set version = '0.5.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ggridges
  version: {{ version|replace("-", "_") }}

source:
  fn: ggridges_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/ggridges_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggridges/ggridges_{{ version }}.tar.gz
  sha256: 124bc84044e56728fa965682f8232fc868f2af7d3eb7276f6b0df53be8d2dbfe

build:
  merge_build_host: True  # [win]
  number: 1
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-ggplot2 >=2.2.0
    - r-plyr >=1.8.0
    - r-scales >=0.4.1
    - r-withr >=2.1.1
  run:
    - r-base
    - r-ggplot2 >=2.2.0
    - r-plyr >=1.8.0
    - r-scales >=0.4.1
    - r-withr >=2.1.1

test:
  commands:
    - $R -e "library('ggridges')"           # [not win]
    - "\"%R%\" -e \"library('ggridges')\""  # [win]

about:
  home: https://github.com/clauswilke/ggridges
  license: GPL-2
  summary: Ridgeline plots provide a convenient way of visualizing changes in distributions over
    time or space. This package enables the creation of such plots in 'ggplot2'.
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-2'  # [win]

extra:
  recipe-maintainers:
    - rvalieris
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
