{% set version = '0.5.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ggridges
  version: {{ version|replace("-", "_") }}

source:
  fn: ggridges_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/ggridges_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggridges/ggridges_{{ version }}.tar.gz
  sha256: 01f87cdcdf2052ed9c078d9352465cdeda920a41e2ca55bc154c1574fc651c36

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 1000
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:

  host:
    - r-base
    - r-ggplot2 >=2.2.0
    - r-plyr >=1.8.0
    - r-scales >=0.4.1
    - r-withr >=2.1.1
  run:
    - r-base
    - r-ggplot2 >=2.2.0
    - r-plyr >=1.8.0
    - r-scales >=0.4.1
    - r-withr >=2.1.1

test:
  commands:
    - $R -e "library('ggridges')"           # [not win]
    - "\"%R%\" -e \"library('ggridges')\""  # [win]

about:
  home: https://github.com/clauswilke/ggridges
  license: GPL-2
  summary: Ridgeline plots provide a convenient way of visualizing changes in distributions over
    time or space. This package enables the creation of such plots in 'ggplot2'.
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - rvalieris
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
