# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_R=3.3.2
    - CONDA_R=3.4.1
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Z1YNDuBGqYA0zMKQTpUZeLMIwRXXoQjZ0ToZA7I7GTzDvD6bF5s0gWVdqynGdxudCOccaJQr3DtRDpCyBO5MsPT+Ez+XCs3y/z+sHSnrCHWe3rncqNB3dyu9R068G7s/ox+L7NbjydtMfD383+Ybh8ENtN4E91yE0jdbeue3MT62i4WqVM4YnvlbNKR/c+kzo/6qT7qhbiIHlyhRJs5UohL0bEKrQQxWOqs30IIjiUuqREdtxx0v/zxeuWl9hVALM2kZZtCiXbsab25mIvpRy9SafHXq5Qka7JFsAxY1FJbaTUk8xYEvWIJBcJS6N/j/a3SLB2yLQ6iEJvw0N/hBsKZ2cjTtqqEWk/SvUza2B9JgEiGn9/pKmObZDO5j+FKIwcuHt6pRqd/lrHT/niBLUbY1jmqtOl+fHe7lNQ98AjNjumSpisfpYKPUoOF/OKMe/3UQpImW0H1AORCV+ORcj2j/9FqyhxDqfXtuJhgsW79ydS8HNRCdGOWOg5NaptaufjLkCfAmCDcm/+xiQGvYzp+gtRBtxK9EclhSP31CcmKlHAPFODUAmETOkTiFdCYVHKkWFoW7VYp06VfsP3HWLGERmWdEc55W5SlEpGSwM9M4BLYvkKPPTFZxCSoz2ywBOJeePJX15nwK4yJ7gkwmtxlqqO8DPsTp7eU/A1Kjd3k="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
